# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2e4664482ba2ae895362b953675b34a6c4ec6e29d6b3e546694d3f6aa6fbfc3de5933a225d5e357946daf47d3ab2d8d34a2bffcbff457d36e51eedfed5dc5840

test:
  secret_key_base: 91baf9936613aa962c4045cb43b411432a6083331718a1cff58045728b286ce2d40f157d6efeee5d716c8756749e1683b64e688e0ad94232de5d8012bb7772fd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
